### ISSUE TITLE
[3.0] Style of Boolean fields in ValidationRule list views is don't match detail view

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/nautobot#7924]
### Environment
* Nautobot version (Docker tag too if applicable): 3.0.0a1 (next.demo.nautobot.com)
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to: https://next.demo.nautobot.com/data-validation/regex-rules/
2. Observe the style of the 'Enabled' and 'Context processing' fields
3. Click one of the rules and observe the style of those fields in the detail view
4. Go to https://next.demo.nautobot.com/wireless/wireless-networks/
5. Notice the style of the Booleans in the `WirelessNetwork` list views

### Expected Behavior
Style to be consistent with the rest of Nautobot.

### Observed Behavior
It isn't; see above.

**Comment by itdependsnetworks** [comment]
I think this is fixed here: https://github.com/nautobot/nautobot/pull/7722/files#diff-c9dd01bd675028118fa72601dddb7ebb3e240f1d1e50daad77c5aeeed731bb8dR25

**Comment by nrnvgh** [comment]
Based solely on a quick glance at the code, I suspect it's only partially fixed there; I'm guessing it's fixed on `enabled` but still wrong on `context_processing`.

**Comment by itdependsnetworks** [comment]
fixed in #7722
